/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-04-15 01:36:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;

public final class loginPro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>member.loginPro.jsp</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t");

	request.setCharacterEncoding("utf-8");
	
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      com.itwillbs.member.memberBean mb = null;
      mb = (com.itwillbs.member.memberBean) _jspx_page_context.getAttribute("mb", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mb == null){
        mb = new com.itwillbs.member.memberBean();
        _jspx_page_context.setAttribute("mb", mb, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("mb"), request);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
 
	System.out.println("전달정보:" +mb);
	
	
	String DRIVER = "com.mysql.jdbc.Driver";
    String DBURL = "jdbc:mysql://localhost:3306/jspdb";
    String DBID ="root";
    String DBPW ="1234";
   
    //2. 드라이버연결 
    Class.forName(DRIVER);
    
  Connection conn = DriverManager.getConnection(DBURL, DBID, DBPW);
  
  //3. sql구문 & pstmt객체 생성
  String sql ="select pw from itwill_member where id=?";
    
  PreparedStatement pstmt = conn.prepareStatement(sql);
  
  pstmt.setString(1, mb.getId());
  
  //4. sql구문 실행
ResultSet rs = pstmt.executeQuery();
  
  //5. 데이터 처리
  if(rs.next()){ //sql구문의 결과가 있을때 
	  //회원이다.
	  //비밀번호를 사용해서 본인확인
	  if(mb.getPw().equals(rs.getString("pw")) ){
		 //비밀번호 같다(+회원이다) =>본인 => 로그인성공
		
		//로그인 성공의 의미로 회원 ID정보를 session내장객체에 저장
		session.setAttribute("id", mb.getId());
		 							//업캐스팅됨 (자동 형변환)
		// main.jsp 페이지 이동		 
		//response.sendRedirect("main.jsp");
		
      out.write("\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\talert(\"로그인 성공!\");\r\n");
      out.write("\t\t\tlocation.href=\"main.jsp\";\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t");
 
		
	  }else{
		  //비밀번호 다름(+회원이다)
		  
      out.write("\r\n");
      out.write("\t\t  <script type=\"text/javascript\">\r\n");
      out.write("\t\t  alert(\"비밀번호가 일치하지 않습니다. 다시 입력해주세요\");\r\n");
      out.write("\t\t  history.back();\r\n");
      out.write("\t\t  </script>\r\n");
      out.write("\t\t  ");
 
	  }
  }else{
	  //비회원이다.
	  
      out.write("\r\n");
      out.write("\t  <script type=\"text/javascript\">\r\n");
      out.write("\t  //confirm(\"회원정보가 없습니다.회원가입하겠습니까?\");\r\n");
      out.write("\t var result = confirm(\"회원정보가 없습니다.회원가입하겠습니까?\");\r\n");
      out.write("\t  \r\n");
      out.write("\t  if(result){\r\n");
      out.write("\t\t  alert(\"회원가입 페이지로 이동합니다\");\r\n");
      out.write("\t\t  location.href = \"insertForm.jsp\";\r\n");
      out.write("\t\t  \r\n");
      out.write("\t  }else{\r\n");
      out.write("\t\t  history.back();\r\n");
      out.write("\t  } \r\n");
      out.write("\t // alert(\"회원정보가 없습니다.\");\r\n");
      out.write("\r\n");
      out.write("\t  </script>\r\n");
      out.write("\t  \r\n");
      out.write("\t   \r\n");
      out.write("\t  ");
 
	  
  }  
  
  
  //문자열 상수
  //String A1 ="itwill";
  //String B1 ="itwill";
  
  //문자열 객체
  //String A = new String("itwill");
  //String B = new String("itwill");
  
	// -> 참조형은 A.equals(B)로 비교해야함!!
	 //참조형은 4바이트..
	//https://cdmanii.com/272
	
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
