/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-04-15 03:32:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import com.itwillbs.member.memberBean;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;
import com.mysql.jdbc.interceptors.SessionAssociationInterceptor;

public final class updateForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.itwillbs.member.memberBean");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.mysql.jdbc.interceptors.SessionAssociationInterceptor");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

  
  String id =(String) session.getAttribute("id");
  
  if (id == null) {
		System.out.println("[info.jsp] : 아이디없음 -> 로그인페이지이동");
		response.sendRedirect("loginForm.jsp");
	}
  
  String DRIVER = "com.mysql.jdbc.Driver";
  String DBURL = "jdbc:mysql://localhost:3306/jspdb";
  String DBID = "root";
  String DBPW = "1234";
  
  
  Class.forName(DRIVER);
  System.out.println("드라이버 로드 성공");
  
  Connection conn = DriverManager.getConnection(DBURL, DBID, DBPW);
  
  String sql = "select * from itwill_member where id=? ";
  
  PreparedStatement pstmt = conn.prepareStatement(sql);
  
  pstmt.setString(1, id);
  
  ResultSet rs = pstmt.executeQuery();
  
  memberBean mb = null;
  if(rs.next()){
	  mb = new memberBean();
		mb.setId(rs.getString("id"));
		mb.setPw(rs.getString("pw"));
		mb.setName(rs.getString("name"));
		mb.setAge(rs.getInt("age"));
		mb.setGender(rs.getString("gender"));
		mb.setEmail(rs.getString("email"));
		mb.setRegdate(rs.getTimestamp("regdate"));
		
	  System.out.println("SQL구문 실행완료!");
	  System.out.println("저장된 회원정보 : " +mb);
	  
  }
  
  
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <h1>WebContent/member/updateForm.jsp</h1>\r\n");
      out.write("  \r\n");
      out.write("  <h2> 회원가입 </h2>\r\n");
      out.write("  <!-- 아이디,비밀번호, 이름,나이, 성별(라디오버튼),이메일 -->\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <fieldset>\r\n");
      out.write("    <legend> 아이티윌 회원가입 페이지 </legend>\r\n");
      out.write("    ");
 if(mb != null) {
      out.write("\r\n");
      out.write("    <form action=\"updatePro.jsp\" method=\"post\">\r\n");
      out.write("    <!-- input  태그\r\n");
      out.write("    \treadonly 속성 : 값 변경 X , 데이터 전송(submit) O\r\n");
      out.write("    \tdisabled 속성 : 값 변경 X , 데이터 전송 X\r\n");
      out.write("    \r\n");
      out.write("     -->\r\n");
      out.write("      아이디 : <input type=\"text\" name=\"id\" value=\"");
      out.print(mb.getId());
      out.write("\" readonly=\"readonly\"><br>\r\n");
      out.write("      비밀번호 : <input type=\"password\" name=\"pw\" placeholder=\"비밀번호를 입력하세요.\"><br>\r\n");
      out.write("      <hr>\r\n");
      out.write("      이름 : <input type=\"text\" name=\"name\" value=\"");
      out.print(mb.getName());
      out.write("\"><br>\r\n");
      out.write("      나이 : <input type=\"number\" name=\"age\" value=\"");
      out.print(mb.getAge());
      out.write("\"><br>\r\n");
      out.write("      성별 : <input type=\"radio\" name=\"gender\" value=\"남\"\r\n");
      out.write("        ");
 
         if(mb.getGender().equals("남")){
        	 
      out.write("\r\n");
      out.write("        \t checked=\"checked\"\r\n");
      out.write("        \t ");

         }
        
      out.write("        \r\n");
      out.write("      > 남\r\n");
      out.write("      <input type=\"radio\" name=\"gender\" value=\"여\"\r\n");
      out.write("         ");
 
         if(mb.getGender().equals("여")){
        	 
      out.write("\r\n");
      out.write("        \t checked\r\n");
      out.write("        \t ");

         }
        
      out.write(" \r\n");
      out.write("      \r\n");
      out.write("      > 여  <br>\r\n");
      out.write("      이메일 : <input type=\"email\" name=\"email\" value=\"");
      out.print(mb.getEmail());
      out.write("\"><br>\r\n");
      out.write("      <hr>\r\n");
      out.write("     <input type=\"submit\" value=\"완료\">           \r\n");
      out.write("    \r\n");
      out.write("    </form>  \r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("  </fieldset>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
